In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Actual Data

In [2]:
# read input data
df = pd.read_csv('INPUT_DATA_ACTUAL.txt')
df.columns = ["hex0", "hex1", "hex2", "hex3","hex4","hex5","hex6","hex7"]
df.head()

hex0  hex1  hex2  hex3  hex4  hex5  hex6  hex7
0     0     4     0     0     0     0     0     0
1     5     6     0     7     0     8     0     9
2     5    10    11    12    11    13    14    15
3    16    17    16    18    16    18     0     0
4    19    20     0     0    16    21     0     0

each row represents a packet  --> observation
each column is a hex value  --> feature - 8 features
1,2,3,0,0,0,0,0

In [3]:
print df

       hex0  hex1  hex2  hex3  hex4  hex5  hex6  hex7
0         0     4     0     0     0     0     0     0
1         5     6     0     7     0     8     0     9
2         5    10    11    12    11    13    14    15
3        16    17    16    18    16    18     0     0
4        19    20     0     0    16    21     0     0
5        22     0     0     0     0     0    23    24
6        25    26    26    27    28    29    23    30
7        31    32    33    34    33    35    31    16
8        30    36     0    37     0    38     0     0
9        16    39    16    20    16    40    16    41
10       36    42    30    43    44    45     0     0
11        0     0     0     0     0     0     0    46
12        0     0     0     0     0     0     0     0
13       22     0     0     0     0     0    23    24
14        0     4     0     0     0     0     0     0
15       47    48    26    49    28    29    50    30
16       51    52    53     0     0     0     0     0
17       16    39    16    2

In [4]:
print(df.shape)

(15677, 8)


In [5]:
# read output data
df2 = pd.read_csv('OUTPUT_DATA_ACTUAL.txt')
df2.columns = ["Classification"]
print df2
# 0-> Autopark
# 1-> Drive
# 2-> Idle

       Classification
0                   0
1                   0
2                   0
3                   0
4                   0
5                   0
6                   0
7                   0
8                   0
9                   0
10                  0
11                  0
12                  0
13                  0
14                  0
15                  0
16                  0
17                  0
18                  0
19                  0
20                  0
21                  0
22                  0
23                  0
24                  0
25                  0
26                  0
27                  0
28                  0
29                  0
...               ...
15647               2
15648               2
15649               2
15650               2
15651               2
15652               2
15653               2
15654               2
15655               2
15656               2
15657               2
15658               2
15659               2
15660     

In [6]:
print(df2.shape)

(15677, 1)


In [7]:
print type(df)
print type(df2)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [8]:
print("\n Features")
df_np=df.values
print df_np
print("\n Response")
df2_np=df2.values
print df2_np
print("\n")


 Features
[[  0   4   0 ...   0   0   0]
 [  5   6   0 ...   8   0   9]
 [  5  10  11 ...  13  14  15]
 ...
 [  5  10  11 ... 110  14  15]
 [  0   4   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]

 Response
[[0]
 [0]
 [0]
 ...
 [2]
 [2]
 [2]]




In [9]:
# feature matrix
x = df_np
# response vector (target) - 0,1,2
y = df2_np

In [10]:
print(df.shape)
print(df2.shape)
print("-----------------")
print(df_np.shape)
print(df2_np.shape)
df2_np=np.ravel(y,order='C')

(15677, 8)
(15677, 1)
-----------------
(15677, 8)
(15677, 1)


# Without Splitting Data

## KNN =1

In [11]:
knn = KNeighborsClassifier(n_neighbors=1)
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [12]:
print("-----------------")
print np.ravel(y,order='C')

knn.fit(x,np.ravel(y,order='C'))  #train the model

-----------------
[0 0 0 ... 2 2 2]


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [13]:
X = [[5,6,0,7,0,8,0,9]]
knn.predict(X)

array([0])

In [14]:
y_pred=knn.predict(x)
from sklearn import metrics
print metrics.accuracy_score(y,y_pred)

0.7778911781590866


## KNN=3

In [15]:
knn = KNeighborsClassifier(n_neighbors=3)
print knn
knn.fit(x,np.ravel(y,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [16]:
X = [[5,6,0,7,0,8,0,9]]
knn.predict(X)

array([0])

In [17]:
y_pred=knn.predict(x)
from sklearn import metrics
print metrics.accuracy_score(y,y_pred)

0.7676213561268099


## KNN=5

In [18]:
knn = KNeighborsClassifier(n_neighbors=5)
print knn
knn.fit(x,np.ravel(y,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [19]:
X = [[5,6,0,7,0,8,0,9]]
knn.predict(X)

array([0])

In [20]:
y_pred=knn.predict(x)
from sklearn import metrics
print metrics.accuracy_score(y,y_pred)

0.7622631881099701


# With Splitting Data

In [21]:
from sklearn.cross_validation import train_test_split

/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [22]:
xx_train,xx_test,yy_train,yy_test=train_test_split(df,df2,test_size=0.2)

## KNN=1

In [23]:
print xx_train.shape
print xx_test.shape

(12541, 8)
(3136, 8)


In [24]:
print yy_train.shape
print yy_test.shape

(12541, 1)
(3136, 1)


In [25]:
knn = KNeighborsClassifier(n_neighbors=1)
print knn
knn.fit(xx_train,np.ravel(yy_train,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [26]:
yy_pred=knn.predict(xx_test)
from sklearn import metrics
print metrics.accuracy_score(yy_test,yy_pred)

0.7480867346938775


## KNN=3

In [27]:
knn = KNeighborsClassifier(n_neighbors=3)
print knn
knn.fit(xx_train,np.ravel(yy_train,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [28]:
yy_pred=knn.predict(xx_test)
from sklearn import metrics
print metrics.accuracy_score(yy_test,yy_pred)

0.7496811224489796


## KNN=5

In [29]:
knn = KNeighborsClassifier(n_neighbors=5)
print knn
knn.fit(xx_train,np.ravel(yy_train,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [30]:
yy_pred=knn.predict(xx_test)
from sklearn import metrics
print metrics.accuracy_score(yy_test,yy_pred)

0.7490433673469388


In [31]:
X = [[19,20,0,0,16,21,0,0]]
knn.predict(X)

array([0])

In [32]:
X = [[5,10,11,88,129,110,14,15]]
knn.predict(X)

array([1])

# Simulated Data

## Without Splitting Data

In [33]:
# read input data
dfs = pd.read_csv('DATA_2_PAIR_SIMULATED_INPUT.txt')
dfs.columns = ["hex0", "hex1", "hex2", "hex3","hex4","hex5","hex6","hex7"]
dfs.head()
print dfs

      hex0  hex1  hex2  hex3  hex4  hex5  hex6  hex7
0        0     0     0     2     0     0     0     3
1        4     4     0     5     0     0     0     0
2        0     0     0     0     0     0     0     6
3        0     0     2     7     8     9     0    10
4        0     0    11    12    13     0     0    14
5       15    16     0    17     0     0     0     0
6        0    18     0     0     0     0     0     0
7       19     0    20    21     0     0     0     9
8        0     0     0     0    22     0     0     0
9        0    23     0     0     0     0     0    18
10       0     0     0     0     0     0     0     1
11       0     0     0     2     0     0     0    24
12       4     4     0     5     0     0     0     0
13       0     0     0     0     0     0     0     6
14       0     0     2     7     8     9     0    10
15       0     0    11    12    25     0     0    26
16      15    16     0    17     0     0     0     0
17       0    27     0     0     0     0     0

In [34]:
# read output data
dfs2 = pd.read_csv('DATA_2_PAIR_SIMULATED_OUTPUT.txt')
dfs2.columns = ["Classification"]
print dfs2
# 0-> Idle
# 1-> Drive

      Classification
0                  0
1                  0
2                  0
3                  0
4                  0
5                  0
6                  0
7                  0
8                  0
9                  0
10                 0
11                 0
12                 0
13                 0
14                 0
15                 0
16                 0
17                 0
18                 0
19                 0
20                 0
21                 0
22                 0
23                 0
24                 0
25                 0
26                 0
27                 0
28                 0
29                 0
...              ...
3565               1
3566               1
3567               1
3568               1
3569               1
3570               1
3571               1
3572               1
3573               1
3574               1
3575               1
3576               1
3577               1
3578               1
3579               1
3580         

In [35]:
# feature matrix
dfs_np = dfs.values
x_sim=dfs_np
# response vector (target) - 0,1
dfs2_np = dfs2.values
y_sim=dfs2_np

## KNN=1

In [36]:
knn = KNeighborsClassifier(n_neighbors=1)
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [37]:
knn.fit(x_sim,np.ravel(y_sim,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [38]:
X = [[4,4,0,5,0,0,0,0]]
knn.predict(X)

array([0])

In [39]:
y_pred=knn.predict(x_sim)
from sklearn import metrics
print metrics.accuracy_score(y_sim,y_pred)

0.6495132127955494


## KNN=3

In [40]:
knn = KNeighborsClassifier(n_neighbors=3)
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')


In [41]:
knn.fit(x_sim,np.ravel(y_sim,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [42]:
X = [[4,4,0,5,0,0,0,0]]
knn.predict(X)
# it shd be 1 not 0

array([0])

In [43]:
y_pred=knn.predict(x_sim)
from sklearn import metrics
print metrics.accuracy_score(y_sim,y_pred)

0.7009735744089013


## KNN=5

In [44]:
knn = KNeighborsClassifier(n_neighbors=5)
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


In [45]:
knn.fit(x_sim,np.ravel(y_sim,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [46]:
X = [[4,4,0,5,0,0,0,0]]
knn.predict(X)
# it shd be 1 not 0

array([0])

In [47]:
y_pred=knn.predict(x_sim)
from sklearn import metrics
print metrics.accuracy_score(y_sim,y_pred)

0.7190542420027817


## With Splitting Data

In [48]:
xx_sim_train,xx_sim_test,yy_sim_train,yy_sim_test=train_test_split(x_sim,y_sim,test_size=0.2)

## KNN = 1

In [49]:
knn = KNeighborsClassifier(n_neighbors=1)
print knn
knn.fit(xx_sim_train,np.ravel(yy_sim_train,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [50]:
yy_pred=knn.predict(xx_sim_test)
from sklearn import metrics
print metrics.accuracy_score(yy_sim_test,yy_pred)

0.6050069541029207


## KNN = 3

In [51]:
knn = KNeighborsClassifier(n_neighbors=3)
print knn
knn.fit(xx_sim_train,np.ravel(yy_sim_train,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [52]:
yy_pred=knn.predict(xx_sim_test)
from sklearn import metrics
print metrics.accuracy_score(yy_sim_test,yy_pred)

0.6884561891515995


# KNN = 5

In [53]:
knn = KNeighborsClassifier(n_neighbors=5)
print knn
knn.fit(xx_sim_train,np.ravel(yy_sim_train,order='C'))  #train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [54]:
yy_pred=knn.predict(xx_sim_test)
from sklearn import metrics
print metrics.accuracy_score(yy_sim_test,yy_pred)

0.713490959666203


# Word2Vec

## Without Splitting Data

## KNN=1

## KNN=3

## KNN=5

## With Splitting Data