In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib import style
import numpy as np
from sklearn.model_selection import train_test_split
style.use('ggplot')

In [2]:
from sklearn import svm
from sklearn.metrics import accuracy_score

# Actual Data

In [3]:
# read input data
df = pd.read_csv('INPUT_DATA_ACTUAL.txt')
df.columns = ["hex0", "hex1", "hex2", "hex3","hex4","hex5","hex6","hex7"]
df.head()

# read output data
df2 = pd.read_csv('OUTPUT_DATA_ACTUAL.txt')
df2.columns = ["Classification"]

In [4]:
print("\n Features")
df_np=df.values
print df_np
print("\n Response")
df2_np=df2.values
print df2_np
print("\n")


 Features
[[  0   4   0 ...   0   0   0]
 [  5   6   0 ...   8   0   9]
 [  5  10  11 ...  13  14  15]
 ...
 [  5  10  11 ... 110  14  15]
 [  0   4   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]

 Response
[[0]
 [0]
 [0]
 ...
 [2]
 [2]
 [2]]




In [5]:
# feature matrix
x = df_np
# response vector (target) - 0,1,2
y = df2_np

In [6]:
print(df.shape)
print(df2.shape)
print("-----------------")
print(df_np.shape)
print(df2_np.shape)
df2_np=np.ravel(y,order='C')

(15677, 8)
(15677, 1)
-----------------
(15677, 8)
(15677, 1)


## No Data Splitting

In [7]:
clf = svm.SVC(gamma=0.001,C=100, kernel='linear')

In [ ]:
clf.fit(x,np.ravel(y,order='C'))

In [ ]:
y_predict = clf.predict(x)

In [ ]:
print metrics.accuracy_score(y,y_predict)

## Data Splitting

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
clf = svm.SVC(gamma=0.001,C=100, kernel='linear')

In [ ]:
clf.fit(x_train,np.ravel(y_train,order='C'))

In [ ]:
y_predict = clf.predict(x_test)

In [ ]:
print metrics.accuracy_score(y_test,y_predict)

# Simulated Data

In [ ]:
# read input data
dfs = pd.read_csv('DATA_2_PAIR_SIMULATED_INPUT.txt')
dfs.columns = ["hex0", "hex1", "hex2", "hex3","hex4","hex5","hex6","hex7"]
dfs.head()
print dfs

In [ ]:
# read output data
dfs2 = pd.read_csv('DATA_2_PAIR_SIMULATED_OUTPUT.txt')
dfs2.columns = ["Classification"]
print dfs2
# 0-> Idle
# 1-> Drive

In [ ]:
# feature matrix
dfs_np = dfs.values
x_sim=dfs_np
# response vector (target) - 0,1
dfs2_np = dfs2.values
y_sim=dfs2_np

## No Data Splitting

In [ ]:
clf = svm.SVC(gamma=0.001,C=100, kernel='linear')
clf.fit(x_sim,np.ravel(y_sim,order='C'))
y_predict = clf.predict(x_sim)
print metrics.accuracy_score(y_sim,y_predict)

## Data Splitting

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_sim,y_sim,test_size=0.2)

In [ ]:
clf = svm.SVC(gamma=0.001,C=100, kernel='linear')
clf.fit(x_train,np.ravel(y_train,order='C'))
y_predict = clf.predict(x_test)
print metrics.accuracy_score(y_test,y_predict)